### ISSUE TITLE
Clarify handling of de-duplicated WARC records

### ISSUE THREAD

**Issue by anjackson** [nla/tinycdxserver#2]
Can you tell me whether you use de-duplicated WARCs? And if so, if there's any trick to setting up playback in this situation?

I've been trying to use your CDX server with WARCs with ```revisit``` records, and it seems to be incompatible with OpenWayback.  AFAICT right now, OWB expects the RemoteCollection to handle the deduplication, and the built-in remote collection handler does not resolve duplicates.  I suspect this is actually a problem with OWB, but I thought I'd ask here in case you've already resolved this issue.

**Comment by ato** [comment]
Alas we don't use de-duplicated WARCs.

Taking a look at the OpenWayback code, I think you're right. It looks like revisits are indicated by a CDX line with a content-type of warc/revisit. That's handled by WARCRevisitAnnotationFilter via AnnotatingCaptureFilterGroup which is only configured for LocalResourceIndex:

https://github.com/iipc/openwayback/blob/a277b1cb11ea6e18c478d491023d97de16bd340c/wayback-core/src/main/java/org/archive/wayback/resourceindex/LocalResourceIndex.java#L134

Hmm. So I guess I see three possible approaches to making it work:

1. Enable WARCRevisitAnnotationFilter for RemoteResourceIndex in OpenWayback.
2. Resolve revisits at indexing time, so the index itself would contain multiple (url, timestamp) keys pointing at the same (filename, offset) record.
3. Store the revisit metadata in the index. I not fully confident of this, but it looks like it may work if tinycdxserver supplies fields "duplicate", "duplicate-ts", "payload-file", "payload-offset" in the xmlquery results it returns to Wayback.

The first option may be the easiest to get working. It might be as simple as adding a single line to RemoteResourceIndex to enable the filter. But perhaps the filter makes assumptions that are only valid for a local index.

Option 2 would require a change to the indexer but not to tinycdxserver or wayback. That is of course assuming wayback doesn't barf when the WARC headers don't match what the index said.

Option 3 would require a change to both the indexer and adding some new fields to tinycdxserver. It may be the better solution technically though as it means the index contains all the necessary information.

**Comment by anjackson** [comment]
Thanks for looking at this. Skimming the code, I think attaching the WARCRevisitAnnotationFilter should work, but I'm not sure how best to proceed. I'll raise this on the OWB mailing list and see if anyone has any ideas.

**Comment by ato** [comment]
Ah, I didn't actually realise OpenWayback included a CDX Server API client. The 'embedded' in the name of EmbeddedCDXServerIndex threw me off. If I had known that I would probably have used that protocol instead.

If revisit resolution works with that protocol then I guess option 4 is teaching tinycdxserver to speak the CDX Server API.

**Comment by anjackson** [comment]
Yes, that's a very badly names class.

I suspect adding a whole additional API to your CDX server is going to be rather a lot of work, so I'll try to find a way of getting OpenWayback to cope with things as they are.

**Comment by anjackson** [comment]
Hm. This tiny change seems to work...

https://github.com/iipc/openwayback/compare/master...ukwa:rri-resolve-revisits#diff-2c5dc073ab2922fd28857f474ee96f28

I'll do more testing and submit a pull request to OWB.

**Comment by anjackson** [comment]
Done. https://github.com/iipc/openwayback/pull/304

**Comment by anjackson** [comment]
Okay, I think this is resolved now - we're using it and it's working just fine with OWB 2.3.0.
